# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
R_ArtmCreateMasterComponent <- function(master_component_config) {
    .Call('bigartm_R_ArtmCreateMasterComponent', PACKAGE = 'bigartm', master_component_config)
}

#' @export
R_ArtmCreateDictionary <- function(master_id, dict_component_config) {
    .Call('bigartm_R_ArtmCreateDictionary', PACKAGE = 'bigartm', master_id, dict_component_config)
}

