# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_ArtmCreateMasterComponent <- function(length, master_component_config) {
    .Call('bigartm_R_ArtmCreateMasterComponent', PACKAGE = 'bigartm', length, master_component_config)
}

