// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// R_ArtmCreateMasterComponent
int R_ArtmCreateMasterComponent(int length, RawVector master_component_config);
RcppExport SEXP bigartm_R_ArtmCreateMasterComponent(SEXP lengthSEXP, SEXP master_component_configSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type length(lengthSEXP);
    Rcpp::traits::input_parameter< RawVector >::type master_component_config(master_component_configSEXP);
    __result = Rcpp::wrap(R_ArtmCreateMasterComponent(length, master_component_config));
    return __result;
END_RCPP
}
