// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// R_ArtmCreateMasterComponent
Int32 R_ArtmCreateMasterComponent(RawVector master_component_config);
RcppExport SEXP bigartm_R_ArtmCreateMasterComponent(SEXP master_component_configSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type master_component_config(master_component_configSEXP);
    __result = Rcpp::wrap(R_ArtmCreateMasterComponent(master_component_config));
    return __result;
END_RCPP
}
// R_ArtmCreateDictionary
Int32 R_ArtmCreateDictionary(Int32 master_id, RawVector dict_component_config);
RcppExport SEXP bigartm_R_ArtmCreateDictionary(SEXP master_idSEXP, SEXP dict_component_configSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Int32 >::type master_id(master_idSEXP);
    Rcpp::traits::input_parameter< RawVector >::type dict_component_config(dict_component_configSEXP);
    __result = Rcpp::wrap(R_ArtmCreateDictionary(master_id, dict_component_config));
    return __result;
END_RCPP
}
